/**
 * DuckDB enum types
 */
/** DUCKDB_TYPE: DuckDB DUCKDB_TYPE enum */
export enum DUCKDB_TYPE {
  /** DUCKDB_TYPE_INVALID = 0 */
  DUCKDB_TYPE_INVALID = 0,
  /** DUCKDB_TYPE_BOOLEAN = 1 */
  DUCKDB_TYPE_BOOLEAN = 1,
  /** DUCKDB_TYPE_TINYINT = 2 */
  DUCKDB_TYPE_TINYINT = 2,
  /** DUCKDB_TYPE_SMALLINT = 3 */
  DUCKDB_TYPE_SMALLINT = 3,
  /** DUCKDB_TYPE_INTEGER = 4 */
  DUCKDB_TYPE_INTEGER = 4,
  /** DUCKDB_TYPE_BIGINT = 5 */
  DUCKDB_TYPE_BIGINT = 5,
  /** DUCKDB_TYPE_UTINYINT = 6 */
  DUCKDB_TYPE_UTINYINT = 6,
  /** DUCKDB_TYPE_USMALLINT = 7 */
  DUCKDB_TYPE_USMALLINT = 7,
  /** DUCKDB_TYPE_UINTEGER = 8 */
  DUCKDB_TYPE_UINTEGER = 8,
  /** DUCKDB_TYPE_UBIGINT = 9 */
  DUCKDB_TYPE_UBIGINT = 9,
  /** DUCKDB_TYPE_FLOAT = 10 */
  DUCKDB_TYPE_FLOAT = 10,
  /** DUCKDB_TYPE_DOUBLE = 11 */
  DUCKDB_TYPE_DOUBLE = 11,
  /** DUCKDB_TYPE_TIMESTAMP = 12 */
  DUCKDB_TYPE_TIMESTAMP = 12,
  /** DUCKDB_TYPE_DATE = 13 */
  DUCKDB_TYPE_DATE = 13,
  /** DUCKDB_TYPE_TIME = 14 */
  DUCKDB_TYPE_TIME = 14,
  /** DUCKDB_TYPE_INTERVAL = 15 */
  DUCKDB_TYPE_INTERVAL = 15,
  /** DUCKDB_TYPE_HUGEINT = 16 */
  DUCKDB_TYPE_HUGEINT = 16,
  /** DUCKDB_TYPE_UHUGEINT = 32 */
  DUCKDB_TYPE_UHUGEINT = 32,
  /** DUCKDB_TYPE_VARCHAR = 17 */
  DUCKDB_TYPE_VARCHAR = 17,
  /** DUCKDB_TYPE_BLOB = 18 */
  DUCKDB_TYPE_BLOB = 18,
  /** DUCKDB_TYPE_DECIMAL = 19 */
  DUCKDB_TYPE_DECIMAL = 19,
  /** DUCKDB_TYPE_TIMESTAMP_S = 20 */
  DUCKDB_TYPE_TIMESTAMP_S = 20,
  /** DUCKDB_TYPE_TIMESTAMP_MS = 21 */
  DUCKDB_TYPE_TIMESTAMP_MS = 21,
  /** DUCKDB_TYPE_TIMESTAMP_NS = 22 */
  DUCKDB_TYPE_TIMESTAMP_NS = 22,
  /** DUCKDB_TYPE_ENUM = 23 */
  DUCKDB_TYPE_ENUM = 23,
  /** DUCKDB_TYPE_LIST = 24 */
  DUCKDB_TYPE_LIST = 24,
  /** DUCKDB_TYPE_STRUCT = 25 */
  DUCKDB_TYPE_STRUCT = 25,
  /** DUCKDB_TYPE_MAP = 26 */
  DUCKDB_TYPE_MAP = 26,
  /** DUCKDB_TYPE_ARRAY = 33 */
  DUCKDB_TYPE_ARRAY = 33,
  /** DUCKDB_TYPE_UUID = 27 */
  DUCKDB_TYPE_UUID = 27,
  /** DUCKDB_TYPE_UNION = 28 */
  DUCKDB_TYPE_UNION = 28,
  /** DUCKDB_TYPE_BIT = 29 */
  DUCKDB_TYPE_BIT = 29,
  /** DUCKDB_TYPE_TIME_TZ = 30 */
  DUCKDB_TYPE_TIME_TZ = 30,
  /** DUCKDB_TYPE_TIMESTAMP_TZ = 31 */
  DUCKDB_TYPE_TIMESTAMP_TZ = 31,
  /** DUCKDB_TYPE_ANY = 34 */
  DUCKDB_TYPE_ANY = 34,
  /** DUCKDB_TYPE_BIGNUM = 35 */
  DUCKDB_TYPE_BIGNUM = 35,
  /** DUCKDB_TYPE_SQLNULL = 36 */
  DUCKDB_TYPE_SQLNULL = 36,
  /** DUCKDB_TYPE_STRING_LITERAL = 37 */
  DUCKDB_TYPE_STRING_LITERAL = 37,
  /** DUCKDB_TYPE_INTEGER_LITERAL = 38 */
  DUCKDB_TYPE_INTEGER_LITERAL = 38,
  /** DUCKDB_TYPE_TIME_NS = 39 */
  DUCKDB_TYPE_TIME_NS = 39,
}

/** duckdb_pending_state: DuckDB pending_state enum */
export enum duckdb_pending_state {
  /** DUCKDB_PENDING_RESULT_READY = 0 */
  DUCKDB_PENDING_RESULT_READY = 0,
  /** DUCKDB_PENDING_RESULT_NOT_READY = 1 */
  DUCKDB_PENDING_RESULT_NOT_READY = 1,
  /** DUCKDB_PENDING_ERROR = 2 */
  DUCKDB_PENDING_ERROR = 2,
  /** DUCKDB_PENDING_NO_TASKS_AVAILABLE = 3 */
  DUCKDB_PENDING_NO_TASKS_AVAILABLE = 3,
}

/** duckdb_result_type: DuckDB result_type enum */
export enum duckdb_result_type {
  /** DUCKDB_RESULT_TYPE_INVALID = 0 */
  DUCKDB_RESULT_TYPE_INVALID = 0,
  /** DUCKDB_RESULT_TYPE_CHANGED_ROWS = 1 */
  DUCKDB_RESULT_TYPE_CHANGED_ROWS = 1,
  /** DUCKDB_RESULT_TYPE_NOTHING = 2 */
  DUCKDB_RESULT_TYPE_NOTHING = 2,
  /** DUCKDB_RESULT_TYPE_QUERY_RESULT = 3 */
  DUCKDB_RESULT_TYPE_QUERY_RESULT = 3,
}

/** duckdb_error_type: DuckDB error_type enum */
export enum duckdb_error_type {
  /** DUCKDB_ERROR_INVALID = 0 */
  DUCKDB_ERROR_INVALID = 0,
  /** DUCKDB_ERROR_OUT_OF_RANGE = 1 */
  DUCKDB_ERROR_OUT_OF_RANGE = 1,
  /** DUCKDB_ERROR_CONVERSION = 2 */
  DUCKDB_ERROR_CONVERSION = 2,
  /** DUCKDB_ERROR_UNKNOWN_TYPE = 3 */
  DUCKDB_ERROR_UNKNOWN_TYPE = 3,
  /** DUCKDB_ERROR_DECIMAL = 4 */
  DUCKDB_ERROR_DECIMAL = 4,
  /** DUCKDB_ERROR_MISMATCH_TYPE = 5 */
  DUCKDB_ERROR_MISMATCH_TYPE = 5,
  /** DUCKDB_ERROR_DIVIDE_BY_ZERO = 6 */
  DUCKDB_ERROR_DIVIDE_BY_ZERO = 6,
  /** DUCKDB_ERROR_OBJECT_SIZE = 7 */
  DUCKDB_ERROR_OBJECT_SIZE = 7,
  /** DUCKDB_ERROR_INVALID_TYPE = 8 */
  DUCKDB_ERROR_INVALID_TYPE = 8,
  /** DUCKDB_ERROR_SERIALIZATION = 9 */
  DUCKDB_ERROR_SERIALIZATION = 9,
  /** DUCKDB_ERROR_TRANSACTION = 10 */
  DUCKDB_ERROR_TRANSACTION = 10,
  /** DUCKDB_ERROR_NOT_IMPLEMENTED = 11 */
  DUCKDB_ERROR_NOT_IMPLEMENTED = 11,
  /** DUCKDB_ERROR_EXPRESSION = 12 */
  DUCKDB_ERROR_EXPRESSION = 12,
  /** DUCKDB_ERROR_CATALOG = 13 */
  DUCKDB_ERROR_CATALOG = 13,
  /** DUCKDB_ERROR_PARSER = 14 */
  DUCKDB_ERROR_PARSER = 14,
  /** DUCKDB_ERROR_PLANNER = 15 */
  DUCKDB_ERROR_PLANNER = 15,
  /** DUCKDB_ERROR_SCHEDULER = 16 */
  DUCKDB_ERROR_SCHEDULER = 16,
  /** DUCKDB_ERROR_EXECUTOR = 17 */
  DUCKDB_ERROR_EXECUTOR = 17,
  /** DUCKDB_ERROR_CONSTRAINT = 18 */
  DUCKDB_ERROR_CONSTRAINT = 18,
  /** DUCKDB_ERROR_INDEX = 19 */
  DUCKDB_ERROR_INDEX = 19,
  /** DUCKDB_ERROR_STAT = 20 */
  DUCKDB_ERROR_STAT = 20,
  /** DUCKDB_ERROR_CONNECTION = 21 */
  DUCKDB_ERROR_CONNECTION = 21,
  /** DUCKDB_ERROR_SYNTAX = 22 */
  DUCKDB_ERROR_SYNTAX = 22,
  /** DUCKDB_ERROR_SETTINGS = 23 */
  DUCKDB_ERROR_SETTINGS = 23,
  /** DUCKDB_ERROR_BINDER = 24 */
  DUCKDB_ERROR_BINDER = 24,
  /** DUCKDB_ERROR_NETWORK = 25 */
  DUCKDB_ERROR_NETWORK = 25,
  /** DUCKDB_ERROR_OPTIMIZER = 26 */
  DUCKDB_ERROR_OPTIMIZER = 26,
  /** DUCKDB_ERROR_NULL_POINTER = 27 */
  DUCKDB_ERROR_NULL_POINTER = 27,
  /** DUCKDB_ERROR_IO = 28 */
  DUCKDB_ERROR_IO = 28,
  /** DUCKDB_ERROR_INTERRUPT = 29 */
  DUCKDB_ERROR_INTERRUPT = 29,
  /** DUCKDB_ERROR_FATAL = 30 */
  DUCKDB_ERROR_FATAL = 30,
  /** DUCKDB_ERROR_INTERNAL = 31 */
  DUCKDB_ERROR_INTERNAL = 31,
  /** DUCKDB_ERROR_INVALID_INPUT = 32 */
  DUCKDB_ERROR_INVALID_INPUT = 32,
  /** DUCKDB_ERROR_OUT_OF_MEMORY = 33 */
  DUCKDB_ERROR_OUT_OF_MEMORY = 33,
  /** DUCKDB_ERROR_PERMISSION = 34 */
  DUCKDB_ERROR_PERMISSION = 34,
  /** DUCKDB_ERROR_PARAMETER_NOT_RESOLVED = 35 */
  DUCKDB_ERROR_PARAMETER_NOT_RESOLVED = 35,
  /** DUCKDB_ERROR_PARAMETER_NOT_ALLOWED = 36 */
  DUCKDB_ERROR_PARAMETER_NOT_ALLOWED = 36,
  /** DUCKDB_ERROR_DEPENDENCY = 37 */
  DUCKDB_ERROR_DEPENDENCY = 37,
  /** DUCKDB_ERROR_HTTP = 38 */
  DUCKDB_ERROR_HTTP = 38,
  /** DUCKDB_ERROR_MISSING_EXTENSION = 39 */
  DUCKDB_ERROR_MISSING_EXTENSION = 39,
  /** DUCKDB_ERROR_AUTOLOAD = 40 */
  DUCKDB_ERROR_AUTOLOAD = 40,
  /** DUCKDB_ERROR_SEQUENCE = 41 */
  DUCKDB_ERROR_SEQUENCE = 41,
  /** DUCKDB_INVALID_CONFIGURATION = 42 */
  DUCKDB_INVALID_CONFIGURATION = 42,
}

/** duckdb_cast_mode: DuckDB cast_mode enum */
export enum duckdb_cast_mode {
  /** DUCKDB_CAST_NORMAL = 0 */
  DUCKDB_CAST_NORMAL = 0,
  /** DUCKDB_CAST_TRY = 1 */
  DUCKDB_CAST_TRY = 1,
}
